version: '3'

services:
  backend:
    build: ./backend
    container_name: pokecrud_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pokemonDB
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: pokecrud_frontend
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL=http://backend:3000/api/pokemon
    depends_on:
      - backend

  mongo:
    image: mongo@lastest
    container_name: pokecrud_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
